# Generated by Django 5.2.5 on 2025-11-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestorUser', '0001_initial'),
        ('sensores', '0002_dispositivo_latitud_dispositivo_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUGA', 'Posible Fuga Detectada'), ('EXCESO', 'Consumo Excesivo'), ('OFFLINE', 'Sensor Desconectado'), ('INFO', 'Resumen/Información')], max_length=10)),
                ('mensaje', models.TextField(help_text='Descripción detallada de la alerta')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gestorUser.usuario')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
