# Generated by Django 4.2.25 on 2025-11-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0004_merge_20251114_1622'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_fijo', models.PositiveIntegerField(default=3000, help_text='Monto fijo mensual en CLP')),
                ('limite_tramo_1', models.FloatField(default=15, help_text='Límite del primer tramo en m³')),
                ('valor_tramo_1', models.PositiveIntegerField(default=500, help_text='Valor por m³ en Tramo 1 (CLP)')),
                ('valor_tramo_2', models.PositiveIntegerField(default=1000, help_text='Valor por m³ sobre el Tramo 1 (CLP)')),
                ('iva', models.FloatField(default=0.19, help_text='Porcentaje de IVA (ej: 0.19)')),
                ('empresa', models.OneToOneField(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, to='gestorUser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('consumo_m3', models.FloatField(default=0)),
                ('monto_cargo_fijo', models.PositiveIntegerField()),
                ('monto_consumo_variable', models.PositiveIntegerField()),
                ('monto_subsidio', models.PositiveIntegerField(default=0)),
                ('monto_neto', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
                ('estado_sii', models.CharField(default='Pendiente', max_length=50)),
                ('folio_sii', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_boleta', models.FileField(blank=True, null=True, upload_to='boletas/')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='boletas_recibidas', to='gestorUser.usuario')),
                ('empresa', models.ForeignKey(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='boletas_emitidas', to='gestorUser.usuario')),
                ('tarifa_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.tarifa')),
            ],
            options={
                'unique_together': {('cliente', 'mes', 'ano')},
            },
        ),
    ]
