# Generated by Django 4.2.25 on 2025-11-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_tarifa_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='iva',
            field=models.FloatField(default=0.19, help_text='Porcentaje de IVA (Ej: 0.19 para 19%)'),
        ),
    ]
