# Generated by Django 4.2.25 on 2025-11-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0005_remove_usuario_direccion_empresa_and_more'),
        ('reportes', '0003_alter_tarifa_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'organizacion_admin__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='boletas_recibidas', to='gestorUser.usuario'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_emitidas', to='gestorUser.organizacion'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='iva',
            field=models.FloatField(default=0.19, help_text='Porcentaje de IVA (ej: 0.19)'),
        ),
    ]
