# Generated by Django 4.2.25 on 2025-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_remove_tarifa_empresa_alter_boleta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago Real'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Ej: Transferencia, Efectivo, Cheque', max_length=50),
        ),
    ]
