# Generated by Django 4.2.25 on 2025-11-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0004_dispositivo_es_propiedad_empresa'),
        ('gestorUser', '0005_remove_usuario_direccion_empresa_and_more'),
        ('reportes', '0005_boleta_estado_pago_boleta_fecha_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Fuga Nocturna', max_length=100)),
                ('flujo_maximo', models.FloatField(help_text='Límite de flujo permitido (L/min)')),
                ('duracion_minima', models.PositiveIntegerField(default=1, help_text='Minutos consecutivos que debe mantenerse el flujo alto para alertar')),
                ('hora_inicio', models.TimeField(default='00:00')),
                ('hora_fin', models.TimeField(default='23:59')),
                ('dias_semana', models.CharField(default='0,1,2,3,4,5,6', help_text='Días activos (0=Lunes)', max_length=50)),
                ('enviar_email', models.BooleanField(default=False, help_text='Enviar correo si se rompe la regla')),
                ('activa', models.BooleanField(default=True)),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a todos', null=True, on_delete=django.db.models.deletion.CASCADE, to='sensores.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_alerta', to='gestorUser.usuario')),
            ],
        ),
    ]
