# Generated by Django 4.2.25 on 2025-11-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_consumo_mensual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
