# Generated by Django 4.2.25 on 2025-11-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa_asociada',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'EMPRESA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_administrados', to='gestorUser.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente Final'), ('EMPRESA', 'Empresa Distribuidora')], default='CLIENTE', max_length=10),
        ),
    ]
