# Generated by Django 5.2.5 on 2025-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0002_usuario_limite_consumo_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='limite_consumo_mensual',
            field=models.PositiveIntegerField(default=10000, help_text='Límite de consumo mensual total en Litros'),
        ),
    ]
