# Generated by Django 4.2.25 on 2025-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0002_usuario_direccion_usuario_empresa_asociada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección de la Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_cliente',
            field=models.CharField(blank=True, help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT del Cliente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_empresa',
            field=models.CharField(blank=True, help_text='Ej: 76.123.456-K', max_length=12, verbose_name='RUT de la Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección del Cliente'),
        ),
    ]
