# Generated by Django 4.2.25 on 2025-11-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0003_alter_usuario_limite_consumo_mensual'),
        ('gestorUser', '0003_usuario_direccion_empresa_usuario_rut_cliente_and_more'),
    ]

    operations = [
    ]
