# Generated by Django 4.2.25 on 2025-11-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_tarifa_iva'),
        ('gestorUser', '0004_merge_20251114_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='empresa_asociada',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut_empresa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT del Cliente'),
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=12, verbose_name='RUT de la Empresa')),
                ('direccion_empresa', models.CharField(blank=True, max_length=255, verbose_name='Dirección de la Empresa')),
                ('tarifa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion', to='reportes.tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='organizacion_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_administrados', to='gestorUser.organizacion'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_interno', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado')], default='EMPLEADO', max_length=20)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gestorUser.organizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gestorUser.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'organizacion')},
            },
        ),
    ]
