# Generated by Django 4.2.25 on 2025-11-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestorUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dispositivo_mqtt', models.CharField(help_text='El ID único usado en los mensajes MQTT', max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='gestorUser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_flujo', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.dispositivo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
