# Generated by Django 4.2.25 on 2025-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
