# Generated by Django 4.2.25 on 2025-11-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_dispositivo_latitud_dispositivo_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='limite_flujo_excesivo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
