# Generated by Django 4.2.25 on 2025-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_dispositivo_limite_flujo_excesivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='es_propiedad_empresa',
            field=models.BooleanField(default=False, help_text='Si es True, el cliente no puede eliminar este sensor.'),
        ),
    ]
